# Do not add your user, or any others, to this group.
group_name=onepassword-cli
binary_path=/usr/bin/op

group_exists() {
  getent group "$1" >/dev/null
}

ensure_group() {
  group_exists "$1" || groupadd "$1"
}

setup_binary() {
  chgrp "$1" "$2"
  chmod g+s "$2"
}

pre_install() {
  ensure_group "${group_name}"
}

pre_upgrade() {
  pre_install
}

post_install() {
  setup_binary "${group_name}" "${binary_path}"
}

post_upgrade() {
  post_install
}

post_remove() {
  if group_exists "${group_name}"; then
    groupdel "${group_name}"
  fi
}
