name: ShellCheck

on:
  push:
    paths:
      - '**.sh'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install --yes shellcheck

      - name: Check shell scripts
        run: shellcheck --shell=bash build.sh create.sh lint.sh

      - name: Check GitHub Actions workflows
        uses: docker://rhysd/actionlint:1.7.12
